# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'eSignaturePDF' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod "EPSignature"
  # Pods for eSignaturePDF

end
